### ISSUE TITLE
Pre-trained Models

### ISSUE THREAD

**Issue by ltnghia** [xunguangwang/ProS-GAN#3]
Hi,
This is a great job!
Can you release your pre-trained models?
Thanks!

**Comment by xunguangwang** [comment]
> Hi,
> This is a great job!
> Can you release your pre-trained models?
> Thanks!

https://drive.google.com/drive/folders/1q7Pk940obiHrRd4MUfIikZdBGkt3ElD4?usp=sharing

**Comment by ltnghia** [comment]
Thank you!
