### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/NUS-WIDE\\images/0041_184606467.jpg'

### ISSUE THREAD

**Issue by xiaoweidao** [xunguangwang/ProS-GAN#4]
After running the hashing code, the file data/NUS-WIDE\\images/0041_184606467.jpg cannot be found

**Comment by xunguangwang** [comment]
> After running the hashing code, the file data/NUS-WIDE\images/0041_184606467.jpg cannot be found

Hi! It may be that the data you downloaded is different from mine. I probably referred to this website (https://github.com/thuml/HashNet/tree/master/pytorch#datasets) for downloading NUS-WIDE.

**Comment by xiaoweidao** [comment]
> > After running the hashing code, the file data/NUS-WIDE\images/0041_184606467.jpg cannot be found
> 
> Hi! It may be that the data you downloaded is different from mine. I probably referred to this website (https://github.com/thuml/HashNet/tree/master/pytorch#datasets) for downloading NUS-WIDE.


Sorry to disturb you, I just used your data set, but this error still occurs.

**Comment by xiaoweidao** [comment]
> > > After running the hashing code, the file data/NUS-WIDE\images/0041_184606467.jpg cannot be found
> > 
> > 
> > Hi! It may be that the data you downloaded is different from mine. I probably referred to this website (https://github.com/thuml/HashNet/tree/master/pytorch#datasets) for downloading NUS-WIDE.
> 
> Sorry to disturb you, I just used your data set, but this error still occurs.


Thank you. I know the solution. The data set has not been downloaded.
