### ISSUE TITLE
No such file or directory: './checkpoint/ImageNet_DPSH_VGG11_32.pth'

### ISSUE THREAD

**Issue by jingzhang697** [xunguangwang/ProS-GAN#5]
hello,
    When running main.py, there is a model-free error. The two models I saw in checkpoint are not the same as the error. I don't know if I can use them. What should I do? Come to consult, hope to get your answer, thank you very much.

**Comment by xunguangwang** [comment]
> 

Well, I think you first need to run hashing.py to get the "xx_DPSH_xx.pth". Then, you can run the main.py.

**Comment by jingzhang697** [comment]
hello,
&nbsp; &nbsp;&nbsp;Thank you very much for your answer. I have a question. I didn't find the file hashing.py in all the folders of the code file. Can you provide it again? thank you.






------------------ 原始邮件 ------------------
发件人:                                                                                                                        "xunguangwang/ProS-GAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月10日(星期五) 晚上9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xunguangwang/ProS-GAN] No such file or directory: './checkpoint/ImageNet_DPSH_VGG11_32.pth' (Issue #5)





   
Well, I think you first need to run hashing.py to get the "xx_DPSH_xx.pth". Then, you can run the main.py.

**Comment by xunguangwang** [comment]
> 
https://github.com/xunguangwang/ProS-GAN/blob/main/hashing.py
